export const bloodDonationRejectedReasons = [
  { label: "Low Hemoglobin Level", value: "LOW_HEMOGLOBIN" },
  { label: "Underweight", value: "UNDERWEIGHT" },
  { label: "Overweight", value: "OVERWEIGHT" },
  { label: "High Blood Pressure", value: "HIGH_BP" },
  { label: "Low Blood Pressure", value: "LOW_BP" },
  { label: "Recent Illness or Infection", value: "RECENT_ILLNESS" },
  { label: "Fever on Donation Day", value: "FEVER" },
  { label: "Cold, Cough, or Flu", value: "COLD_COUGH_FLU" },
  { label: "Recent Surgery", value: "RECENT_SURGERY" },
  { label: "Recent Tattoo or Piercing", value: "RECENT_TATTOO_PIERCING" },
  { label: "On Certain Medications", value: "MEDICATION_RESTRICTION" },
  { label: "History of Blood Transfusion (Recent)", value: "RECENT_TRANSFUSION" },
  { label: "Pregnant or Recently Delivered", value: "PREGNANT_OR_POST_DELIVERY" },
  { label: "Alcohol Consumption (Last 24 Hours)", value: "ALCOHOL_CONSUMPTION" },
  { label: "Chronic Medical Condition", value: "CHRONIC_CONDITION" },
  { label: "Infectious Disease Risk", value: "INFECTIOUS_DISEASE_RISK" },
  { label: "Age Not Eligible", value: "AGE_NOT_ELIGIBLE" },
  { label: "Donated Blood Recently", value: "RECENT_DONATION" },
  { label: "Failed Medical Screening", value: "FAILED_SCREENING" },
  { label: "Other Medical Reasons", value: "OTHER_MEDICAL_REASON" }
];
